name: Build Android APK with Flask backend

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Install Android SDK
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools.zip
        rm commandlinetools.zip
        mv cmdline-tools latest
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.1.8937393"
    - name: Add SDK tools to PATH
      run: |
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/ndk/25.1.8937393" >> $GITHUB_PATH
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - run: |
        pip install --upgrade pip
        pip install -r flask_backend/requirements.txt
    - run: chmod +x android/gradlew
    - run: ./gradlew assembleDebug --stacktrace
      working-directory: android
    - uses: actions/upload-artifact@v4
      with:
        name: FaceApp-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
